name: Unit tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/plugin
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-node@v4.0.3
        with:
          node-version-file: "apps/plugin/.nvmrc"
      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 6.0.2
      - name: Install dependencies
        run: pnpm install
      - name: Run unit tests
        run: pnpm test
